# Generated by Django 3.2.9 on 2021-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuboid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuboid',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
