# Generated by Django 3.2.9 on 2021-11-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuboid', '0002_cuboid_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuboid',
            name='area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuboid',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
